# src/open_source_risk_model/feature_mappings/option_c.py
# -----------------------------------------------------------------------------
# option_c.py
#
# Percentile-based (empirical CDF) risk mapping.
# Converts a raw numeric value into a percentile score using baseline population
# data, optionally applying a shape transform (e.g. power or log) to control
# risk separation across the distribution.
#
# Requires a baseline JSON population file generated by github_repo_sampling.py
# and configured in feature_mapping_config.py.
# -----------------------------------------------------------------------------

from bisect import bisect_right
from typing import Sequence


def apply_option_c(value: float, population_values: Sequence[float]) -> float:
    """
    Quantile-style risk mapping (Option C).

    Given:
      - value: the raw feature value for a repo
      - population_values: a sequence of that feature's values across repos

    Returns:
      - risk in [0, 1], equal to the empirical CDF:
        proportion of population_values <= value
    """
    vals = sorted(population_values)
    n = len(vals)
    if n == 0:
        raise ValueError("population_values must be non-empty")

    # index of the first element > value
    idx = bisect_right(vals, value)

    # empirical CDF = fraction of values <= value
    return idx / n
